databases:
  - name: breaking-cypher-db
    plan: free
    databaseName: breaking-cypher-web
    user: breaking-cypher

services:
  - type: web
    name: breaking-cypher-web
    env: python
    plan: free
    branch: production
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.2
      - key: DATABASE_URL
        fromDatabase:
          name: breaking-cypher-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.production
      - key: WEB_CONCURRENCY
        value: 4