# Generated by Django 4.1.4 on 2022-12-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_article_content_article_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_url',
        ),
        migrations.AddField(
            model_name='article',
            name='article_data',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='<function uuid4 at 0x00000243CA039120>', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='匿名ID', max_length=200, primary_key=True, serialize=False),
        ),
    ]
