# Generated by Django 4.1.4 on 2022-12-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_article_article_url_article_article_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
