# Generated by Django 4.1.4 on 2022-12-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_article_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='', editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
