# Generated by Django 4.1.4 on 2022-12-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_article_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeforofficial',
            name='user_id',
            field=models.OneToOneField(default='default_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.user'),
        ),
        migrations.CreateModel(
            name='UserAnsweredArticle',
            fields=[
                ('answer_user_id', models.ForeignKey(default='default_answer_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.user')),
                ('article_id', models.ForeignKey(default='default_article_id', on_delete=django.db.models.deletion.CASCADE, to='app1.article')),
            ],
        ),
    ]
