# Generated by Django 4.1.4 on 2022-12-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_timeforofficial_user_id_useransweredarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='useransweredarticle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useransweredarticle',
            name='answer_user_id',
            field=models.ForeignKey(default='default_answer_user_id', on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
